import { useEffect, useMemo, useState } from 'react';
import {
  Archive, BarChart3, Bell, BookOpen, ChevronRight, CircleDollarSign, Cloud,
  CloudOff, Leaf, LogOut, Menu, Moon, MoreHorizontal, PawPrint, Plus, Settings,
  ShieldCheck, Sprout, Sun, Tractor, Users, Wheat, X, Trash2, FileDown,
} from 'lucide-react';
import { clearSession, FarmData, getFarmData, login, savedSession, saveFarmData, User } from './api';

type Section = 'dashboard' | 'finance' | 'reports' | 'settings' | string;
type Module = { id: string; label: string; description: string; icon: typeof PawPrint; collections: string[]; color: string; products?: string[]; routines?: string[]; fields: Array<{ key: string; label: string; type?: string; placeholder?: string; options?: string[] }> };
type FarmConfig = { enabled: string[]; archived: string[]; configured: boolean; county?: string };
type Row = Record<string, unknown>;

const modules: Module[] = [
  { id: 'cattle', label: 'Cattle', description: 'Dairy cows, beef cattle, calves and breeding records', icon: PawPrint, collections: ['cows', 'calves'], color: '#397bb8', fields: [{ key: 'tag', label: 'Animal tag / name', placeholder: 'e.g. COW-014' }, { key: 'breed', label: 'Breed', placeholder: 'e.g. Friesian' }, { key: 'sex', label: 'Sex', type: 'select' }, { key: 'birthDate', label: 'Birth date', type: 'date' }, { key: 'purpose', label: 'Purpose', placeholder: 'Dairy, beef, breeding' }, { key: 'purchasePrice', label: 'Purchase value (KES)', type: 'number' }] },
  { id: 'sheep-goats', label: 'Sheep & goats', description: 'Sheep, dairy goats, meat goats and breeding stock', icon: PawPrint, collections: ['sheep', 'goats'], color: '#a97837', fields: [{ key: 'tag', label: 'Tag / name', placeholder: 'e.g. GOAT-006' }, { key: 'species', label: 'Species', placeholder: 'Sheep or goat' }, { key: 'breed', label: 'Breed' }, { key: 'sex', label: 'Sex', type: 'select' }, { key: 'birthDate', label: 'Birth date', type: 'date' }, { key: 'purpose', label: 'Purpose', placeholder: 'Milk, meat, breeding' }] },
  { id: 'pigs', label: 'Pigs', description: 'Sows, boars, piglets and commercial pork production', icon: PawPrint, collections: ['pigs', 'pigBatches'], color: '#c26462', fields: [{ key: 'tag', label: 'Tag / pen', placeholder: 'e.g. PEN-03' }, { key: 'breed', label: 'Breed' }, { key: 'count', label: 'Number of pigs', type: 'number' }, { key: 'stage', label: 'Production stage', placeholder: 'Sow, grower, finisher' }, { key: 'arrivalDate', label: 'Arrival date', type: 'date' }] },
  { id: 'rabbits', label: 'Rabbits', description: 'Breeding, grow-out and commercial rabbit meat', icon: PawPrint, collections: ['rabbits'], color: '#7e9caa', fields: [{ key: 'tag', label: 'Tag / cage', placeholder: 'e.g. CAGE-08' }, { key: 'breed', label: 'Breed' }, { key: 'sex', label: 'Sex', type: 'select' }, { key: 'birthDate', label: 'Birth date', type: 'date' }, { key: 'purpose', label: 'Purpose' }] },
  { id: 'poultry', label: 'Poultry', description: 'Layers, broilers, kienyeji, breeders and hatchery', icon: Leaf, collections: ['poultry', 'eggRecords'], color: '#d18b35', products: ['Layers', 'Broilers', 'Kienyeji', 'Ducks', 'Geese', 'Turkeys', 'Guinea fowl', 'Quail', 'Breeding flock', 'Hatchery'], routines: ['Brooding and temperature checks', 'Feed and water records', 'Vaccination schedule', 'Mortality and health records', 'Egg collection and grading', 'Weight and growth checks', 'House cleaning and biosecurity', 'Sales and dispatch'], fields: [{ key: 'batchName', label: 'Flock / batch name', placeholder: 'e.g. Broilers July' }, { key: 'birdType', label: 'Bird type' }, { key: 'count', label: 'Bird count', type: 'number' }, { key: 'arrivalDate', label: 'Arrival date', type: 'date' }, { key: 'source', label: 'Source / supplier' }] },
  { id: 'dairy', label: 'Dairy & milk', description: 'Milk production, quality, buyers and dairy products', icon: Tractor, collections: ['milkRecords', 'dairyProducts'], color: '#5b83b5', products: ['Raw milk', 'Yoghurt', 'Mala / fermented milk', 'Cheese', 'Butter', 'Cream'], routines: ['Morning and evening milking', 'Animal health and mastitis checks', 'Milk quality and rejection records', 'Cooling and storage', 'Feed and water monitoring', 'Buyer collection and sales', 'Cleaning and hygiene'], fields: [{ key: 'date', label: 'Record date', type: 'date' }, { key: 'animalTag', label: 'Animal / herd', placeholder: 'e.g. COW-014 or morning herd' }, { key: 'litres', label: 'Litres produced', type: 'number' }, { key: 'session', label: 'Session' }, { key: 'buyer', label: 'Buyer / destination' }] },
  { id: 'crops', label: 'Field crops & grains', description: 'Maize, wheat, beans, potatoes, oats and other field crops', icon: Wheat, collections: ['plots', 'plotSeasons', 'cropActivities'], color: '#4c9650', products: ['Maize', 'Wheat', 'Beans', 'Potatoes (Shangi)', 'Oats', 'Barley', 'Rice', 'Sorghum', 'Millet', 'Peas', 'Sunflower', 'Canola', 'Sugarcane'], routines: ['Land preparation', 'Seed selection and planting', 'Fertilizer application', 'Weeding and crop protection', 'Irrigation / rainfall monitoring', 'Scouting and disease records', 'Harvest and post-harvest handling'], fields: [{ key: 'plotName', label: 'Plot / field name', placeholder: 'e.g. North field' }, { key: 'crop', label: 'Crop' }, { key: 'area', label: 'Area (acres)', type: 'number' }, { key: 'plantedDate', label: 'Planting / start date', type: 'date' }, { key: 'expectedCompletion', label: 'Expected harvest / completion', type: 'date' }, { key: 'variety', label: 'Variety / seed', placeholder: 'e.g. Shangi' }] },
  { id: 'vegetables', label: 'Vegetables', description: 'Open-field and greenhouse vegetable production', icon: Sprout, collections: ['vegetableBatches'], color: '#3d9b76', products: ['Tomatoes', 'Kale / sukuma wiki', 'Cabbage', 'Onions', 'Carrots', 'Spinach', 'Capsicum', 'Cucumber', 'French beans', 'Peas', 'Lettuce', 'Broccoli', 'Cauliflower', 'Pumpkin', 'Sweet corn'], routines: ['Nursery / seedling management', 'Bed preparation and planting', 'Irrigation scheduling', 'Fertilizer and fertigation', 'Weeding and pruning', 'Pest and disease scouting', 'Spraying and withholding period', 'Harvest grading and packing'], fields: [{ key: 'plotName', label: 'Plot / greenhouse', placeholder: 'e.g. Greenhouse 2' }, { key: 'crop', label: 'Vegetable' }, { key: 'area', label: 'Area (m² or acres)', type: 'number' }, { key: 'plantedDate', label: 'Planting date', type: 'date' }, { key: 'expectedHarvest', label: 'Expected harvest', type: 'date' }] },
  { id: 'fruits', label: 'Fruit & tree crops', description: 'Orchards, berries, bananas, avocado and tree crops', icon: Leaf, collections: ['orchards', 'fruitHarvests'], color: '#5c9a52', products: ['Avocado', 'Banana', 'Mango', 'Passion fruit', 'Strawberry', 'Pineapple', 'Papaya', 'Tree tomato', 'Apple', 'Orange', 'Lemon', 'Guava', 'Macadamia', 'Coffee', 'Tea'], routines: ['Nursery and planting', 'Mulching and irrigation', 'Pruning and canopy management', 'Fertilizer application', 'Pest and disease scouting', 'Flowering and fruit-set monitoring', 'Harvest maturity checks', 'Sorting, packing and cold storage'], fields: [{ key: 'block', label: 'Orchard / block' }, { key: 'crop', label: 'Fruit / tree' }, { key: 'treeCount', label: 'Trees / plants', type: 'number' }, { key: 'plantingDate', label: 'Planting date', type: 'date' }, { key: 'variety', label: 'Variety' }] },
  { id: 'flowers-herbs', label: 'Flowers & herbs', description: 'Flowers, herbs, spices and high-value horticulture', icon: Sprout, collections: ['flowerBatches', 'herbBatches'], color: '#a85e9e', fields: [{ key: 'crop', label: 'Flower / herb', placeholder: 'Roses, mint, coriander...' }, { key: 'block', label: 'Block / greenhouse' }, { key: 'area', label: 'Area', type: 'number' }, { key: 'plantedDate', label: 'Planting date', type: 'date' }] },
  { id: 'aquaculture', label: 'Fish farming', description: 'Ponds, stocking, feed and fish harvests', icon: Leaf, collections: ['ponds', 'fishRecords'], color: '#398e9b', fields: [{ key: 'pondName', label: 'Pond name', placeholder: 'e.g. Pond 1' }, { key: 'species', label: 'Fish species', placeholder: 'Tilapia, catfish' }, { key: 'count', label: 'Stocked quantity', type: 'number' }, { key: 'stockingDate', label: 'Stocking date', type: 'date' }, { key: 'feed', label: 'Feed used' }] },
  { id: 'apiary', label: 'Beekeeping', description: 'Hives, honey, wax and other bee products', icon: Leaf, collections: ['hives', 'honeyRecords'], color: '#b17b2d', fields: [{ key: 'hiveName', label: 'Hive identifier', placeholder: 'e.g. HIVE-12' }, { key: 'hiveType', label: 'Hive type' }, { key: 'apiary', label: 'Apiary location' }, { key: 'colonizedDate', label: 'Colonized date', type: 'date' }, { key: 'notes', label: 'Notes' }] },
  { id: 'processing', label: 'Processing & products', description: 'Flour, yoghurt, juice, feeds and packaged foods', icon: BookOpen, collections: ['products', 'productionBatches'], color: '#8a5eab', fields: [{ key: 'productName', label: 'Product name', placeholder: 'e.g. Avexi yoghurt' }, { key: 'batchNumber', label: 'Batch number' }, { key: 'quantity', label: 'Quantity produced', type: 'number' }, { key: 'unit', label: 'Unit', placeholder: 'kg, litres, packets' }, { key: 'productionDate', label: 'Production date', type: 'date' }, { key: 'expiryDate', label: 'Expiry date', type: 'date' }] },
  { id: 'sales', label: 'Commercial sales & stock', description: 'Customers, orders, inventory, invoices and deliveries', icon: CircleDollarSign, collections: ['customers', 'orders', 'inventory'], color: '#bd5b52', fields: [{ key: 'customer', label: 'Customer / buyer' }, { key: 'product', label: 'Product sold' }, { key: 'quantity', label: 'Quantity', type: 'number' }, { key: 'amount', label: 'Sale value (KES)', type: 'number' }, { key: 'date', label: 'Sale date', type: 'date' }, { key: 'paymentStatus', label: 'Payment status', placeholder: 'Paid, credit, partial' }] },
  { id: 'equipment', label: 'Equipment & machinery', description: 'Tractors, tools, vehicles, maintenance and fuel', icon: Tractor, collections: ['equipment', 'maintenanceRecords'], color: '#667a83', fields: [{ key: 'name', label: 'Equipment name' }, { key: 'assetNumber', label: 'Asset number' }, { key: 'purchaseDate', label: 'Purchase date', type: 'date' }, { key: 'purchaseValue', label: 'Value (KES)', type: 'number' }, { key: 'condition', label: 'Condition' }] },
  { id: 'staff', label: 'Farm staff', description: 'Employees, contractors, payroll and responsibilities', icon: Users, collections: ['staff', 'staffPayments'], color: '#647b5b', fields: [{ key: 'name', label: 'Full name' }, { key: 'role', label: 'Role / responsibility' }, { key: 'phone', label: 'Phone number' }, { key: 'startDate', label: 'Start date', type: 'date' }, { key: 'monthlySalary', label: 'Monthly salary (KES)', type: 'number' }] },
];
const baseNav = [
  { id: 'dashboard', label: 'Overview', icon: BarChart3 },
  { id: 'finance', label: 'Finance', icon: CircleDollarSign },
  { id: 'reports', label: 'Reports', icon: BookOpen },
  { id: 'settings', label: 'Farm setup', icon: Settings },
] as const;
const emptyData: FarmData = { cows: [], sheep: [], milkRecords: [], transactions: [], staff: [], plotSeasons: [], vetVisits: [] };

function count(items: unknown) { return Array.isArray(items) ? items.filter((row) => (row as Row).archived !== true && (row as Row).status !== 'sold' && (row as Row).status !== 'dead').length : 0; }
function totalRows(data: FarmData, module: Module) { return module.collections.reduce((n, key) => n + (Array.isArray(data[key]) ? (data[key] as unknown[]).length : 0), 0); }
function money(value: number) { return new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES', maximumFractionDigits: 0 }).format(value); }
function getConfig(data: FarmData): FarmConfig {
  const config = data.farmConfig as Partial<FarmConfig> | undefined;
  if (config?.configured) return { enabled: config.enabled || [], archived: config.archived || [], configured: true, county: config.county || 'Nyandarua' };
  const inferred = modules.filter((module) => totalRows(data, module) > 0).map((module) => module.id);
  return { enabled: inferred.length ? inferred : ['cattle', 'crops', 'dairy'], archived: [], configured: false, county: 'Nyandarua' };
}

export default function App() {
  const [session, setSession] = useState(savedSession);
  const [data, setData] = useState<FarmData>(emptyData);
  const [section, setSection] = useState<Section>('dashboard');
  const [dark, setDark] = useState(() => localStorage.getItem('avexi_theme') === 'dark');
  const [online, setOnline] = useState(false);
  const [loading, setLoading] = useState(Boolean(session));
  const [error, setError] = useState('');
  const [setupOpen, setSetupOpen] = useState(false);

  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; localStorage.setItem('avexi_theme', dark ? 'dark' : 'light'); }, [dark]);
  useEffect(() => {
    if (!session) return;
    getFarmData(session.token).then((result) => {
      const next = result.data || emptyData; setData(next); setOnline(true);
      if (!(next.farmConfig as FarmConfig | undefined)?.configured) setSetupOpen(true);
    }).catch((err: Error) => setError(err.message)).finally(() => setLoading(false));
  }, [session]);
  if (!session) return <Login onLogin={setSession} />;
  if (loading) return <div className="loading-screen">Loading your farm workspace…</div>;

  const config = getConfig(data);
  const visibleModules = modules.filter((module) => config.enabled.includes(module.id) || config.archived.includes(module.id));
  const activeModules = visibleModules.filter((module) => !config.archived.includes(module.id));
  const canViewFinance = session.user.role !== 'staff';
  const transactions = Array.isArray(data.transactions) ? data.transactions as Array<Row & { type?: string; amount?: number }> : [];
  const income = transactions.filter((t) => t.type === 'income').reduce((sum, t) => sum + Number(t.amount || 0), 0);
  const expenses = transactions.filter((t) => t.type === 'expense').reduce((sum, t) => sum + Number(t.amount || 0), 0);
  const persist = async (next: FarmData) => { setData(next); try { await saveFarmData(session.token, next); setOnline(true); } catch (err) { setOnline(false); setError((err as Error).message); } };
  const signOut = () => { clearSession(); setSession(null); };
  const selectedModule = modules.find((module) => module.id === section);
  const title = selectedModule?.label || baseNav.find((item) => item.id === section)?.label || 'Overview';

  return <div className="app-shell">
    <header><button className="icon mobile-only" onClick={() => document.body.classList.toggle('nav-open')} aria-label="Open menu"><Menu /></button><div className="brand"><span className="brand-mark">◌</span><span>Avexi</span></div><span className="header-context">Commercial farm workspace</span><div className="header-spacer" /><span className={`sync ${online ? 'online' : ''}`}>{online ? <Cloud size={14} /> : <CloudOff size={14} />} {online ? 'Synced' : 'Offline'}</span><button className="icon" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Sun /> : <Moon />}</button><button className="icon" onClick={signOut} aria-label="Sign out"><LogOut /></button></header>
    <div className="layout"><aside><div className="nav-title">Workspace</div><nav>{baseNav.filter(({ id }) => id !== 'finance' || canViewFinance).map(({ id, label, icon: Icon }) => <button key={id} className={section === id ? 'nav-link active' : 'nav-link'} onClick={() => { setSection(id); document.body.classList.remove('nav-open'); }}><Icon size={17} /><span>{label}</span><ChevronRight size={14} /></button>)}</nav><div className="nav-title module-title">My operations</div><nav>{activeModules.map((module) => { const Icon = module.icon; return <button key={module.id} className={section === module.id ? 'nav-link active module-link' : 'nav-link module-link'} style={{ '--module-color': module.color } as React.CSSProperties} onClick={() => { setSection(module.id); document.body.classList.remove('nav-open'); }}><Icon size={17} /><span>{module.label}</span><ChevronRight size={14} /></button>; })}</nav>{config.archived.length > 0 && <button className="archived-link" onClick={() => setSetupOpen(true)}><Archive size={15} /> Archived areas ({config.archived.length})</button>}<div className="aside-user"><strong>{session.user.full_name}</strong><span>{session.user.role}</span></div></aside>
      <main><div className="page-heading"><div><p className="eyebrow">Avexi Farm · {config.county}</p><h1>{title}</h1><p className="subheading">Track production, stock and commercial performance in one place.</p></div><div className="heading-actions"><button className="secondary" onClick={() => setSetupOpen(true)}><Plus size={16} /> Add operation</button><div className="user-pill">{session.user.full_name} · {session.user.role}</div></div></div>{error && <div className="notice error">{error}</div>}{section === 'dashboard' ? <Dashboard activeModules={activeModules} data={data} income={income} expenses={expenses} onOpen={(id) => setSection(id)} /> : section === 'finance' && canViewFinance ? <Finance data={data} income={income} expenses={expenses} onSave={persist} farmerName={session.user.full_name} /> : section === 'reports' ? <Reports data={data} activeModules={activeModules} /> : section === 'settings' ? <SetupCard config={config} onOpen={() => setSetupOpen(true)} /> : selectedModule ? <ModuleView module={selectedModule} data={data} archived={config.archived.includes(selectedModule.id)} role={session.user.role} onSave={persist} /> : <Dashboard activeModules={activeModules} data={data} income={income} expenses={expenses} onOpen={(id) => setSection(id)} />}</main></div>
    {setupOpen && <SetupModal config={config} data={data} onClose={() => setSetupOpen(false)} onSave={async (next) => { await persist(next); setSetupOpen(false); }} />}
  </div>;
}

function Login({ onLogin }: { onLogin: (session: { token: string; user: User }) => void }) {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setBusy(true); try { onLogin(await login(username.trim(), password)); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } };
  return <div className="auth"><div className="auth-art"><span className="brand-mark">◌</span><p>Avexi Farm</p><h2>Run the farm<br />like a business.</h2></div><div className="auth-card"><div className="brand auth-brand"><span className="brand-mark">◌</span><span>Avexi</span></div><p className="eyebrow">Commercial farm management</p><h1>Welcome back</h1><p className="muted">Manage production, people, products and sales with clarity.</p><form onSubmit={submit}>{error && <div className="notice error">{error}</div>}<label>Username<input required value={username} onChange={(e) => setUsername(e.target.value)} autoComplete="username" /></label><label>Password<input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" /></label><button className="primary full" disabled={busy}>{busy ? 'Signing in…' : 'Sign in'}</button></form></div></div>;
}

function Dashboard({ activeModules, data, income, expenses, onOpen }: { activeModules: Module[]; data: FarmData; income: number; expenses: number; onOpen: (id: string) => void }) {
  const milk = (data.milkRecords as Row[] || []).filter((row) => row.date === new Date().toISOString().slice(0, 10)).reduce((sum, row) => sum + Number(row.litres || 0), 0);
  return <><div className="welcome-card"><div><span className="eyebrow">Today at a glance</span><h2>Your operation, your priorities.</h2><p>Choose the business areas you run. Avexi keeps your workspace focused while protecting every historical record.</p></div><button className="primary" onClick={() => onOpen('finance')}>View performance <ChevronRight size={16} /></button></div><div className="stats"><Stat label="Active areas" value={activeModules.length} tone="green" /><Stat label="Tracked animals" value={count(data.cows) + count(data.sheep) + count(data.calves)} tone="blue" /><Stat label="Today's milk" value={`${milk.toFixed(1)} L`} tone="purple" /><Stat label="Net balance" value={money(income - expenses)} tone={income - expenses >= 0 ? 'green' : 'red'} /></div><div className="section-heading"><div><h2>My operations</h2><p className="muted">Open an area to manage its records.</p></div><span className="badge">{activeModules.length} active</span></div><div className="operation-grid">{activeModules.map((module) => <button className="operation-card" key={module.id} onClick={() => onOpen(module.id)}><span className="operation-icon" style={{ background: `${module.color}18`, color: module.color }}><module.icon size={22} /></span><span><strong>{module.label}</strong><small>{module.description}</small><em>{totalRows(data, module)} records</em></span><ChevronRight size={17} /></button>)}</div><div className="content-grid"><section className="card"><div className="card-title"><h2>Recent activity</h2><span className="muted">{(data.transactions as unknown[] || []).length} transactions</span></div>{(data.transactions as Row[] || []).slice(-5).reverse().map((item, index) => <div className="list-row" key={String(item.id || index)}><span>{String(item.category || item.desc || 'Farm transaction')}<small>{String(item.date || 'No date')}</small></span><strong className={item.type === 'income' ? 'positive' : 'negative'}>{item.type === 'income' ? '+' : '-'}{money(Number(item.amount || 0))}</strong></div>)}{!(data.transactions as unknown[] || []).length && <Empty text="Your recent production and sales activity will appear here." />}</section><section className="card insight-card"><div className="card-title"><h2>Workspace rule</h2><ShieldCheck size={18} /></div><p>Areas with records can never be deleted. Archive them instead, so reports and audit history remain intact.</p><button className="text-button" onClick={() => onOpen('settings')}>Manage farm areas <ChevronRight size={15} /></button></section></div></>;
}
function Stat({ label, value, tone }: { label: string; value: string | number; tone: string }) { return <div className={`stat ${tone}`}><span>{label}</span><strong>{value}</strong></div>; }

function ModuleView({ module, data, archived, role, onSave }: { module: Module; data: FarmData; archived: boolean; role: User['role']; onSave: (data: FarmData) => Promise<void> }) {
  const rows: Row[] = module.collections.flatMap((key) => Array.isArray(data[key]) ? (data[key] as Row[]).map((row) => ({ ...row, _collection: key })) : []);
  const [formOpen, setFormOpen] = useState(false);
  const [editing, setEditing] = useState<Row | null>(null);
  const saveRecord = (values: Row) => {
    const collection = String(editing?._collection || module.collections[0]);
    const existing = Array.isArray(data[collection]) ? data[collection] as Row[] : [];
    const record = { ...values, id: editing?.id || crypto.randomUUID(), status: editing?.status || 'active', createdAt: editing?.createdAt || new Date().toISOString() };
    const nextRows = editing ? existing.map((row) => row.id === editing.id ? record : row) : [...existing, record];
    const amount = Number(values.financeAmount || values.amount || (module.id === 'sales' ? values.amount : 0) || 0);
    const financeType = values.financeType || (module.id === 'sales' ? 'income' : amount && module.id === 'staff' ? 'expense' : '');
    const transactions = Array.isArray(data.transactions) ? data.transactions : [];
    const linkedTransaction = amount > 0 && financeType ? { id: crypto.randomUUID(), type: financeType, amount, category: String(values.financeCategory || module.label), desc: String(values.desc || values.product || values.crop || module.label), date: String(values.date || values.plantedDate || values.productionDate || new Date().toISOString().slice(0, 10)), sourceId: record.id } : null;
    const nextTransactions = linkedTransaction ? (editing ? transactions.map((transaction) => transaction.sourceId === record.id ? { ...transaction, ...linkedTransaction, id: transaction.id } : transaction).concat(transactions.some((transaction) => transaction.sourceId === record.id) ? [] : [linkedTransaction]) : [...transactions, linkedTransaction]) : transactions;
    setFormOpen(false); setEditing(null); void onSave({ ...data, [collection]: nextRows, transactions: nextTransactions });
  };
  const archiveRecord = (row: Row) => {
    const collection = String(row._collection);
    const existing = Array.isArray(data[collection]) ? data[collection] as Row[] : [];
    void onSave({ ...data, [collection]: existing.map((item) => item.id === row.id ? { ...item, archived: true, status: 'archived' } : item) });
  };
  const deleteRecord = (row: Row) => {
    if (!window.confirm('Permanently delete this record? This cannot be undone.')) return;
    if (!window.confirm('Confirm permanent deletion again. Continue?')) return;
    const collection = String(row._collection);
    const existing = Array.isArray(data[collection]) ? data[collection] as Row[] : [];
    void onSave({ ...data, [collection]: existing.filter((item) => item.id !== row.id) });
  };
  return <section className="card section-card"><div className="section-hero" style={{ '--module-color': module.color } as React.CSSProperties}><div className="hero-icon"><module.icon size={28} /></div><div><span className="eyebrow">{archived ? 'Archived area' : 'Active operation'}</span><h2>{module.label}</h2><p>{module.description}</p></div>{role !== 'staff' && !archived && <button className="primary" onClick={() => setFormOpen(true)}><Plus size={16} /> Add record</button>}</div>{archived && <div className="notice archived-notice"><Archive size={16} /> This area is archived. Its history remains available for reports.</div>}{rows.length ? <div className="table-wrap"><table><thead><tr><th>Record</th><th>Type</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id || index)}><td><strong>{String(row.name || row.tag || row.plotName || row.crop || row.batchName || row.productName || row.customer || row.desc || `Record ${index + 1}`)}</strong></td><td>{String(row._collection)}</td><td><span className={`badge ${row.archived ? 'gray' : ''}`}>{String(row.status || 'recorded')}</span></td><td>{String(row.date || row.createdAt || row.plantedDate || row.productionDate || '—').slice(0, 10)}</td><td className="row-actions">{role !== 'staff' && !archived && <><button className="text-button" onClick={() => { setEditing(row); setFormOpen(true); }}>Edit</button><button className="text-button danger-text" onClick={() => archiveRecord(row)}>Archive</button><button className="text-button danger-text" onClick={() => deleteRecord(row)} title="Permanent delete"><Trash2 size={14} /></button></>}</td></tr>)}</tbody></table></div> : <Empty text={`No ${module.label.toLowerCase()} records yet. Add your first record to get started.`} />}{formOpen && <RecordModal module={module} initial={editing || undefined} onClose={() => { setFormOpen(false); setEditing(null); }} onSave={saveRecord} />}</section>;
}

function RecordModal({ module, initial, onClose, onSave }: { module: Module; initial?: Row; onClose: () => void; onSave: (values: Row) => void }) {
  const [values, setValues] = useState<Row>(initial || {});
  const update = (key: string, value: unknown) => setValues((current) => ({ ...current, [key]: value }));
  const selectedProduct = String(values.product || '');
  return <div className="modal-backdrop"><form className="record-modal" onSubmit={(event) => { event.preventDefault(); onSave(values); }}><div className="modal-header"><div><span className="eyebrow">New record</span><h2>Add to {module.label}</h2><p>Record the asset, crop, product or batch, then follow its production routine.</p></div><button type="button" className="icon" onClick={onClose} aria-label="Close">Close</button></div><div className="record-form">{module.products && <label className="form-wide">Product or enterprise<select required value={selectedProduct} onChange={(event) => update('product', event.target.value)}><option value="">Select an option…</option>{module.products.map((product) => <option key={product}>{product}</option>)}</select></label>}{module.fields.map((field) => <label key={field.key}>{field.label}{field.type === 'select' || field.options ? <select required value={String(values[field.key] || '')} onChange={(event) => update(field.key, event.target.value)}><option value="">Select…</option>{(field.options || ['Male', 'Female', 'Mixed']).map((option) => <option key={option}>{option}</option>)}</select> : <input required={field.key !== 'notes'} type={field.type || 'text'} value={String(values[field.key] || '')} placeholder={field.placeholder} onChange={(event) => update(field.key, event.target.value)} />}</label>)}<fieldset className="finance-link"><legend>Link a financial record (optional)</legend><label>Entry type<select value={String(values.financeType || "")} onChange={(event) => update("financeType", event.target.value)}><option value="">No ledger entry</option><option value="expense">Expense</option><option value="income">Income</option></select></label><label>Amount (KES)<input type="number" min="0" value={String(values.financeAmount || "")} onChange={(event) => update("financeAmount", event.target.value)} /></label><label>Category<input value={String(values.financeCategory || "")} placeholder={module.label} onChange={(event) => update("financeCategory", event.target.value)} /></label></fieldset>{module.routines && selectedProduct && <fieldset className="routine-list"><legend>{selectedProduct} routine tracking</legend>{module.routines.map((routine) => <label key={routine} className="routine-item"><input type="checkbox" checked={Array.isArray(values.routines) && values.routines.includes(routine)} onChange={(event) => { const current = Array.isArray(values.routines) ? values.routines as string[] : []; update('routines', event.target.checked ? [...current, routine] as unknown as string : current.filter((item) => item !== routine) as unknown as string); }} /><span>{routine}</span></label>)}</fieldset>}</div><div className="modal-footer"><span className="muted">Records are retained for history and reporting.</span><div><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" type="submit">Save record</button></div></div></form></div>;
}
function Finance({ data, income, expenses, onSave, farmerName }: { data: FarmData; income: number; expenses: number; onSave: (data: FarmData) => Promise<void>; farmerName: string }) {
  const transactions = (data.transactions as Row[] || []); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [formOpen, setFormOpen] = useState(false);
  const filtered = transactions.filter((row) => (!from || String(row.date || '') >= from) && (!to || String(row.date || '') <= to));
  const add = (values: Row) => { void onSave({ ...data, transactions: [...transactions, { ...values, id: crypto.randomUUID(), amount: Number(values.amount || 0) }] }); setFormOpen(false); };
  const exportPdf = () => { const popup = window.open('', '_blank'); if (!popup) return; popup.document.write(`<html><body><h1>Avexi Farm finance report</h1><p>Farmer: ${farmerName}</p><p>Period: ${from || 'All time'} � ${to || 'Today'}</p><h2>Net result: ${money(income - expenses)}</h2><p>Farmer signature: ____________________ &nbsp; Date: __________</p></body></html>`); popup.document.close(); popup.print(); };
  const filteredIncome = filtered.filter((row) => row.type === 'income').reduce((sum, row) => sum + Number(row.amount || 0), 0);
  const filteredExpenses = filtered.filter((row) => row.type === 'expense').reduce((sum, row) => sum + Number(row.amount || 0), 0);
  return <><div className="stats"><Stat label="Income" value={money(filteredIncome)} tone="green" /><Stat label="Expenses" value={money(filteredExpenses)} tone="red" /><Stat label="Net result" value={money(filteredIncome - filteredExpenses)} tone="purple" /></div><section className="card section-card"><div className="card-title"><div><h2>Transactions</h2><p className="muted">Production, sales, costs and payroll in one ledger.</p></div><div className="heading-actions"><button className="secondary" onClick={exportPdf}><FileDown size={15} /> Export / print</button><button className="primary" onClick={() => setFormOpen(true)}><Plus size={16} /> Add transaction</button></div></div><div className="date-filter"><label>From<input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label>To<input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></label><span className="muted">{filtered.length} matching entries</span></div>{filtered.length ? <div className="table-wrap"><table><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Amount</th></tr></thead><tbody>{filtered.slice().reverse().map((row, i) => <tr key={String(row.id || i)}><td>{String(row.date || '�')}</td><td>{String(row.desc || row.category || 'Transaction')}</td><td><span className="badge">{String(row.type || 'expense')}</span></td><td className={row.type === 'income' ? 'positive' : 'negative'}>{money(Number(row.amount || 0))}</td></tr>)}</tbody></table></div> : <Empty text="No financial records in this period." />}</section>{formOpen && <FinanceModal onClose={() => setFormOpen(false)} onSave={add} />}</>;
}
function FinanceModal({ onClose, onSave }: { onClose: () => void; onSave: (values: Row) => void }) { const [values, setValues] = useState<Row>({ type: 'expense', date: new Date().toISOString().slice(0, 10) }); return <div className="modal-backdrop"><form className="record-modal" onSubmit={(e) => { e.preventDefault(); onSave(values); }}><div className="modal-header"><h2>Add finance entry</h2><button type="button" className="icon" onClick={onClose}>Close</button></div><div className="record-form"><label>Type<select value={String(values.type)} onChange={(e) => setValues({ ...values, type: e.target.value })}><option value="expense">Expense</option><option value="income">Income</option></select></label><label>Date<input required type="date" value={String(values.date)} onChange={(e) => setValues({ ...values, date: e.target.value })} /></label><label>Amount (KES)<input required min="0" type="number" value={String(values.amount || '')} onChange={(e) => setValues({ ...values, amount: e.target.value })} /></label><label>Description<input required value={String(values.desc || '')} onChange={(e) => setValues({ ...values, desc: e.target.value })} /></label></div><div className="modal-footer"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Save entry</button></div></form></div>; }function Reports({ data, activeModules }: { data: FarmData; activeModules: Module[] }) { return <section className="card section-card"><div className="section-hero"><div className="hero-icon"><BookOpen /></div><div><span className="eyebrow">Management reporting</span><h2>Commercial reports</h2><p>Build reports from the areas you have selected. Archived data remains included.</p></div></div><div className="report-grid">{activeModules.map((module) => <div className="report-card" key={module.id}><module.icon size={18} /><strong>{module.label}</strong><span>{totalRows(data, module)} records available</span><button className="text-button">Open report <ChevronRight size={14} /></button></div>)}</div></section>; }
function SetupCard({ config, onOpen }: { config: FarmConfig; onOpen: () => void }) { return <section className="card setup-card"><span className="eyebrow">Farm workspace</span><h2>Choose what your farm does</h2><p>Enable areas you currently operate. Nothing with history is ever deleted; stopped operations are archived.</p><div className="setup-summary"><strong>{config.enabled.length}</strong><span>active areas</span><strong>{config.archived.length}</strong><span>archived areas</span></div><button className="primary" onClick={onOpen}>Manage operation areas <ChevronRight size={16} /></button></section>; }
function SetupModal({ config, data, onClose, onSave }: { config: FarmConfig; data: FarmData; onClose: () => void; onSave: (data: FarmData) => Promise<void> }) {
  const [selected, setSelected] = useState(config.enabled); const [archived, setArchived] = useState(config.archived); const groups: Record<string, string[]> = { Livestock: ['cattle', 'sheep-goats', 'pigs', 'rabbits'], Poultry: ['poultry'], Dairy: ['dairy'], 'Field crops': ['crops'], Vegetables: ['vegetables'], Fruits: ['fruits', 'flowers-herbs'], Aquaculture: ['aquaculture'], Beekeeping: ['apiary'], Processing: ['processing', 'sales'], 'Equipment & staff': ['equipment', 'staff'] };
  const toggle = (id: string) => { if (archived.includes(id)) setArchived(archived.filter((item) => item !== id)); setSelected(selected.includes(id) ? selected.filter((item) => item !== id) : [...selected, id]); };
  const archive = (id: string) => { setSelected(selected.filter((item) => item !== id)); setArchived(archived.includes(id) ? archived.filter((item) => item !== id) : [...archived, id]); };
  return <div className="modal-backdrop"><div className="setup-modal"><div className="modal-header"><div><span className="eyebrow">Workspace setup � Nyandarua</span><h2>Choose your farm enterprises</h2><p>Select the areas you operate. You can add or archive them later without losing history.</p></div><button className="icon" onClick={onClose} aria-label="Close"><X /></button></div><div className="module-picker">{Object.entries(groups).map(([group, ids]) => <div className="picker-group" key={group}><h3>{group}</h3>{ids.map((id) => { const module = modules.find((item) => item.id === id)!; const active = selected.includes(id); const isArchived = archived.includes(id); return <div className={`picker-card ${active ? 'selected' : ''} ${isArchived ? 'archived' : ''}`} key={module.id}><button onClick={() => toggle(module.id)}><span className="picker-icon" style={{ color: module.color }}><module.icon size={21} /></span><span><strong>{module.label}</strong><small>{module.description}</small></span><span className="check">{active ? '?' : isArchived ? 'Archived' : ''}</span></button>{isArchived ? <button className="archive-action restore" onClick={() => toggle(module.id)}>Restore</button> : active && totalRows(data, module) > 0 ? <button className="archive-action" onClick={() => archive(module.id)}><Archive size={13} /> Archive</button> : null}</div>; })}</div>)}</div><div className="modal-footer"><span className="muted">Your selection shapes the dashboard; data is never silently removed.</span><button className="primary" onClick={() => void onSave({ ...data, farmConfig: { enabled: selected, archived, configured: true, county: 'Nyandarua' } })}>Save workspace</button></div></div></div>;
}function Empty({ text }: { text: string }) { return <div className="empty">{text}</div>; }

